#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#include "php_panda.h"
#include "panda_expend.h"
#include "expends/mysql/mysql.h"
#include "expends/mysqli/mysqli.h"
#include "expends/pdo/pdo.h"
#include "expends/memcache/memcache.h"
#include "expends/memcached/memcached.h"
#include "expends/redis/redis.h"
#include "expends/curl/curl.h"
#include "expends/standard/standard.h"

ZEND_EXTERN_MODULE_GLOBALS(panda);

int panda_expend_init_globals(TSRMLS_D)
{
    PANDA_HASHTABLE_INIT(&PANDA_G(expend_func_table));
    PANDA_HASHTABLE_INIT(&PANDA_G(expend_cls_table));
    return SUCCESS;
}
int panda_expend_destroy_globals(TSRMLS_D)
{

    PANDA_HASHTABLE_DESTROY(&PANDA_G(expend_func_table));
    PANDA_HASHTABLE_DESTROY(&PANDA_G(expend_cls_table));
    return SUCCESS;
}

int panda_expend_init_hooks(TSRMLS_D)
{
    panda_expend_register_func_hooks(TSRMLS_C);
    panda_expend_register_cls_func_hooks(TSRMLS_C);
    return SUCCESS;
}

int panda_expend_destroy_hooks(TSRMLS_D)
{
    return SUCCESS;
}

static inline void panda_expend_register_func_hooks(TSRMLS_D)
{
    HashTable *func_table = &PANDA_G(expend_func_table);
    /* mysql extension */
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MYSQL_FUNC_MYSQL_CONNECT, PANDA_FN(mysql_connect));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MYSQL_FUNC_MYSQL_QUERY, PANDA_FN(mysql_query));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MYSQL_FUNC_MYSQL_SELECT_DB, PANDA_FN(mysql_select_db));

    /* mysqli extension */
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_CONNECT, PANDA_FN(mysqli_connect));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_SELECT_DB, PANDA_FN(mysqli_select_db));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_QUERY, PANDA_FN(mysqli_query));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_PREPARE, PANDA_FN(mysqli_prepare));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_STMT_INIT, PANDA_FN(mysqli_stmt_init));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_STMT_EXECUTE, PANDA_FN(mysqli_stmt_execute));

    /* memcache extension */
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_CONNECT, PANDA_FN(memcache_connect));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_PCONNECT, PANDA_FN(memcache_pconnect));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_ADD_SERVER, PANDA_FN(memcache_add_server));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_SET, PANDA_FN(memcache_set));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_GET, PANDA_FN(memcache_get));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_DELETE, PANDA_FN(memcache_delete));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_CLOSE, PANDA_FN(memcache_close));

    /* curl extension */
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_CURL_FUNC_CURL_INIT, PANDA_FN(curl_init));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_CURL_FUNC_CURL_SETOPT, PANDA_FN(curl_setopt));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_CURL_FUNC_CURL_SETOPT_ARRAY, PANDA_FN(curl_setopt_array));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_CURL_FUNC_CURL_EXEC, PANDA_FN(curl_exec));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_CURL_FUNC_CURL_CLOSE, PANDA_FN(curl_close));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_CURL_FUNC_CURL_MULTI_INIT, PANDA_FN(curl_multi_init));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_CURL_FUNC_CURL_MULTI_CLOSE, PANDA_FN(curl_multi_close));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_CURL_FUNC_CURL_MULTI_ADD_HANDLE, PANDA_FN(curl_multi_add_handle));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_CURL_FUNC_CURL_MULTI_REMOVE_HANDLE, PANDA_FN(curl_multi_remove_handle));
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_CURL_FUNC_CURL_MULTI_EXEC, PANDA_FN(curl_multi_exec));

    /* standard extension */
    PANDA_EXPEND_HOOK_FUNC(func_table, PANDA_EXPENDS_EXT_STANDARD_FUNC_FILE_GET_CONTENTS, PANDA_FN(file_get_contents));
}

static inline void panda_expend_register_cls_func_hooks(TSRMLS_D)
{
    HashTable *cls_table = &PANDA_G(expend_cls_table);;
    /* mysqli extension */
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI, \
            PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_METHOD_MYSQLI, PANDA_MN(mysqli, mysqli));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI, \
            PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_METHOD_QUERY, PANDA_MN(mysqli, query));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI, \
            PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_METHOD_SELECT_DB, PANDA_MN(mysqli, select_db));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI, \
            PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_METHOD_PREPARE, PANDA_MN(mysqli, prepare));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_STMT, \
            PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_STMT_METHOD_EXECUTE, PANDA_MN(mysqli_stmt, execute));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI, \
            PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_METHOD_STMT_INIT, PANDA_MN(mysqli, stmt_init));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_STMT, \
            PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_STMT_METHOD_PREPARE, PANDA_MN(mysqli_stmt, prepare));

    /*pdo extension*/
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_PDO_CLS_PDO, \
            PANDA_EXPENDS_EXT_PDO_CLS_PDO_METHOD_PDO, PANDA_MN(pdo, pdo));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_PDO_CLS_PDO,  \
            PANDA_EXPENDS_EXT_PDO_CLS_PDO_METHOD_QUERY, PANDA_MN(pdo, query));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_PDO_CLS_PDO,  \
            PANDA_EXPENDS_EXT_PDO_CLS_PDO_METHOD_EXEC, PANDA_MN(pdo, exec));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_PDO_CLS_PDO, \
            PANDA_EXPENDS_EXT_PDO_CLS_PDO_METHOD_PREPARE, PANDA_MN(pdo, prepare));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_PDO_CLS_PDO_STATEMENT, \
            PANDA_EXPENDS_EXT_PDO_CLS_PDO_STATEMENT_METHOD_EXECUTE, PANDA_MN(pdostatement, execute));

    /*memcache extension*/
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE,\
            PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_CONNECT, PANDA_MN(memcache, connect));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE,\
            PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_PCONNECT, PANDA_MN(memcache, pconnect));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE,\
            PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_SET, PANDA_MN(memcache, set));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE,\
            PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_GET, PANDA_MN(memcache, get));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE,\
            PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_DELETE, PANDA_MN(memcache, delete));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE,\
            PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_ADD_SERVER, PANDA_MN(memcache, addserver));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE,\
            PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_CLOSE, PANDA_MN(memcache, close));

    /*memcached extension*/
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED,\
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_ADD, PANDA_MN(memcached, add));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED,\
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_ADD_BY_KEY, PANDA_MN(memcached, addbykey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED,\
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_ADD_SERVER, PANDA_MN(memcached, addserver));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED,\
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_ADD_SERVERS, PANDA_MN(memcached, addservers));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_APPEND, PANDA_MN(memcached, append));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_APPEND_BY_KEY, PANDA_MN(memcached, appendbykey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_DECREMENT, PANDA_MN(memcached, decrement));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_DECREMENT_BY_KEY, PANDA_MN(memcached, decrementbykey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_DELETE, PANDA_MN(memcached, delete));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_DELETE_BY_KEY, PANDA_MN(memcached, deletebykey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_DELETE_MULTI, PANDA_MN(memcached, deletemulti));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_DELETE_MULTI_BY_KEY, PANDA_MN(memcached, deletemultibykey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_GET, PANDA_MN(memcached, get));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_GET_DELAYED, PANDA_MN(memcached, getdelayed));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_GET_MULTI, PANDA_MN(memcached, getmulti));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_GET_MULTI_BY_KEY, PANDA_MN(memcached, getmultibykey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_INCREMENT, PANDA_MN(memcached, increment));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_INCREMENT_BY_KEY, PANDA_MN(memcached, incrementbykey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_PREPEND, PANDA_MN(memcached, prepend));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_PREPEND_BY_KEY, PANDA_MN(memcached, prependbykey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_REPLACE, PANDA_MN(memcached, replace));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_REPLACE_BY_KEY, PANDA_MN(memcached, replacebykey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_SET, PANDA_MN(memcached, set));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_SET_BY_KEY, PANDA_MN(memcached, setbykey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_SET_MULTI, PANDA_MN(memcached, setmulti));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_SET_MULTI_BY_KEY, PANDA_MN(memcached, setmultibykey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_FETCH, PANDA_MN(memcached, fetch));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_FETCH_ALL, PANDA_MN(memcached, fetchall));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED, \
            PANDA_EXPENDS_EXT_MEMCACHED_CLS_MEMCACHED_METHOD_QUIT, PANDA_MN(memcached, quit));

    /* redis extension */
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_CONNECT, PANDA_MN(redis, connect));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_OPEN, PANDA_MN(redis, open));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_PCONNECT, PANDA_MN(redis, pconnect));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_POPEN, PANDA_MN(redis, popen));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SELECT, PANDA_MN(redis, select));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_CLOSE, PANDA_MN(redis, close));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_GET, PANDA_MN(redis, get));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SET, PANDA_MN(redis, set));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SETEX, PANDA_MN(redis, setex));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_PSETEX, PANDA_MN(redis, psetex));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SETNX, PANDA_MN(redis, setnx));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_DELETE, PANDA_MN(redis, delete));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_DEL, PANDA_MN(redis, del));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_EXISTS, PANDA_MN(redis, exists));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_INCR, PANDA_MN(redis, incr));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
             PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_INCRBY, PANDA_MN(redis, incrby));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
             PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_INCRBYFLOAT, PANDA_MN(redis, incrbyfloat));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
             PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_DECR, PANDA_MN(redis, decr));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
             PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_DECRBY, PANDA_MN(redis, decrby));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
             PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_MGET, PANDA_MN(redis, mget));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
             PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_GETMULTIPLE, PANDA_MN(redis, getmultiple));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_GETSET, PANDA_MN(redis, getset));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_MOVE, PANDA_MN(redis, move));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_EXPIREAT, PANDA_MN(redis, expireat));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_PEXPIREAT, PANDA_MN(redis, pexpireat));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_KEYS, PANDA_MN(redis, keys));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_GETKEYS, PANDA_MN(redis, getkeys));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_APPEND, PANDA_MN(redis, append));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_GETRANGE, PANDA_MN(redis, getrange));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SETRANGE, PANDA_MN(redis, setrange));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_STRLEN, PANDA_MN(redis, strlen));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_TTL, PANDA_MN(redis, ttl));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_PTTL, PANDA_MN(redis, pttl));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_RENAME, PANDA_MN(redis, rename));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_RENAMEKEY, PANDA_MN(redis, renamekey));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_RENAMENX, PANDA_MN(redis, renamenx));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SORT, PANDA_MN(redis, sort));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_PERSIST, PANDA_MN(redis, persist));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_MSET, PANDA_MN(redis, mset));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_MSETNX, PANDA_MN(redis, msetnx));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HDEL, PANDA_MN(redis, hdel));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HEXISTS, PANDA_MN(redis, hexists));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HGET, PANDA_MN(redis, hget));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HGETALL, PANDA_MN(redis, hgetall));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HINCRBY, PANDA_MN(redis, hincrby));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HINCRBYFLOAT, PANDA_MN(redis, hincrbyfloat));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HKEYS, PANDA_MN(redis, hkeys));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HLEN, PANDA_MN(redis, hlen));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HMSET, PANDA_MN(redis, hmset));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HMGET, PANDA_MN(redis, hmget));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HSET, PANDA_MN(redis, hset));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HSETNX, PANDA_MN(redis, hsetnx));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_HVALS, PANDA_MN(redis, hvals));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_BLPOP, PANDA_MN(redis, blpop));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_BRPOP, PANDA_MN(redis, brpop));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_BRPOPLPUSH, PANDA_MN(redis, brpoplpush));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LINDEX, PANDA_MN(redis, lindex));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LGET, PANDA_MN(redis, lget));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LPOP, PANDA_MN(redis, lpop));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LPUSH, PANDA_MN(redis, lpush));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LPUSHX, PANDA_MN(redis, lpushx));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LRANGE, PANDA_MN(redis, lrange));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LGETRANGE, PANDA_MN(redis, lgetrange));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PADNA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LSET, PANDA_MN(redis, lset));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LTRIM, PANDA_MN(redis, ltrim));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LISTTRIM, PANDA_MN(redis, listtrim));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_RPOP, PANDA_MN(redis, rpop));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_RPOPLPUSH, PANDA_MN(redis, rpoplpush));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_RPUSH, PANDA_MN(redis, rpush));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_RPUSHX, PANDA_MN(redis, rpushx));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LLEN, PANDA_MN(redis, llen));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_LSIZE, PANDA_MN(redis, lsize));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SADD, PANDA_MN(redis, sadd));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SCARD, PANDA_MN(redis, scard));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SSIZE, PANDA_MN(redis, ssize));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SDIFF, PANDA_MN(redis, sdiff));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SDIFFSTORE, PANDA_MN(redis, sdiffstore));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SINTER, PANDA_MN(redis, sinter));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SINTERSTORE, PANDA_MN(redis, sinterstore));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SISMEMBER, PANDA_MN(redis, sismember));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SCONTAINS, PANDA_MN(redis, scontains));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SMEMBERS, PANDA_MN(redis, smembers));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SGETMEMBERS, PANDA_MN(redis, sgetmembers));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SMOVE, PANDA_MN(redis, smove));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SPOP, PANDA_MN(redis, spop));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SRANDMEMBER, PANDA_MN(redis, srandmember));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SREM, PANDA_MN(redis, srem));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SREMOVE, PANDA_MN(redis, sremove));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SUNION, PANDA_MN(redis, sunion));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SUNIONSTORE, PANDA_MN(redis, sunionstore));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZADD, PANDA_MN(redis, zadd));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZCARD, PANDA_MN(redis, zcard));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZSIZE, PANDA_MN(redis, zsize));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZCOUNT, PANDA_MN(redis, zcount));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZINCRBY, PANDA_MN(redis, zincrby));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZRANGE, PANDA_MN(redis, zrange));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZRANGEBYSCORE, PANDA_MN(redis, zrangebyscore));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZREVRANGEBYSCORE, PANDA_MN(redis, zrevrangebyscore));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZRANGEBYLEX, PANDA_MN(redis, zrangebylex));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZRANK, PANDA_MN(redis, zrank));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZREVRANK, PANDA_MN(redis, zrevrank));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZREM, PANDA_MN(redis, zrem));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZDELETE, PANDA_MN(redis, zdelete));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZREMRANGEBYRANK, PANDA_MN(redis, zremrangebyrank));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZDELETERANGEBYRANK, PANDA_MN(redis, zdeleterangebyrank));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZREMRANGEBYSCORE, PANDA_MN(redis, zremrangebyscore));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZDELETERANGEBYSCORE, PANDA_MN(redis, zdeleterangebyscore));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZREVRANGE, PANDA_MN(redis, zrevrange));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZSCORE, PANDA_MN(redis, zscore));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_ZUNION, PANDA_MN(redis, zunion));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_PSUBSCRIBE, PANDA_MN(redis, psubscribe));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_PUBLISH, PANDA_MN(redis, publish));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SUBSCRIBE, PANDA_MN(redis, subscribe));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_PUBSUB, PANDA_MN(redis, pubsub));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_EVAL, PANDA_MN(redis, eval));
    PANDA_EXPEND_HOOK_CLS_FUNC(cls_table, PANDA_EXPENDS_EXT_REDIS_CLS_REDIS, \
            PANDA_EXPENDS_EXT_REDIS_CLS_REDIS_METHOD_SCRIPT, PANDA_MN(redis, script));
}

static inline int panda_expend_hook_func(const char *name, panda_expend_func handler, panda_expend_func *stash TSRMLS_DC)
{
    zend_function *func;
    int status = FAILURE;
    do {
        if (zend_hash_find(CG(function_table), name, PANDA_STRLEN(name), (void **)&func) == SUCCESS) {
            if (stash) {
                *stash = func->internal_function.handler;
            }
            func->internal_function.handler = handler;
            status = SUCCESS;
        } else {
           // php_printf("----%s\n-----", name);
        }
    } while (0);

    return status;
}

static inline int panda_expend_hook_cls_func(const char *cls_name, const char *name, panda_expend_func handler, panda_expend_func *stash TSRMLS_DC)
{
    zend_class_entry **cls_ptr;
    zend_function *func;
    int status = FAILURE;
    do {

//        int count = zend_hash_num_elements(CG(class_table));
//        zend_hash_internal_pointer_reset(CG(class_table));
//        zval **z_item;
//
//        for (int i = 0; i < count; i ++) {
//            char* key;
//            ulong idx;
//            zend_hash_get_current_key(CG(class_table), &key, &idx, 0);
//            php_printf("%s\n", key);
//
//            zend_hash_move_forward(CG(class_table));
//        }
//


        if (zend_hash_find(CG(class_table), cls_name, strlen(cls_name) + 1 , (void **)&cls_ptr) == SUCCESS) {
            zend_class_entry *cls = *cls_ptr;
            if (zend_hash_find(&cls->function_table, name, PANDA_STRLEN(name), (void **)&func) == SUCCESS) {
                if (stash) {
                    *stash = func->internal_function.handler;
                }
                func->internal_function.handler = handler;
                status = SUCCESS;
            } else {
                php_printf("%s:%s\n", cls_name,name);
                php_printf("2222222\n");
            }
        } else {
            php_printf("%s\n", cls_name);
            php_printf("1111111\n");
        }
    } while (0);
    return status;
}
