#ifndef PHP_PANDA_MEMCACHE_H
#define PHP_PANDA_MEMCACHE_H

#define PANDA_EXPENDS_EXT_MEMCACHE_DEFAULT_PROT  11211

#define PANDA_EXPENDS_EXT_MEMCACHE "memcache"
#define PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE "memcache"

#define PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_CONNECT "connect"
#define PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_PCONNECT "pconnect"
#define PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_ADD_SERVER "addserver"
#define PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_SET "set"
#define PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_GET "get"
#define PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_DELETE "delete"
#define PANDA_EXPENDS_EXT_MEMCACHE_CLS_MEMCACHE_METHOD_CLOSE "close"


#define PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_CONNECT "memcache_connect"
#define PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_PCONNECT "memcache_pconnect"
#define PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_ADD_SERVER "memcache_add_server"
#define PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_SET "memcache_set"
#define PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_GET "memcache_get"
#define PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_DELETE "memcache_delete"
#define PANDA_EXPENDS_EXT_MEMCACHE_FUNC_MEMCACHE_CLOSE "memcache_close"

PANDA_METHOD(memcache, connect);
PANDA_METHOD(memcache, pconnect);
PANDA_METHOD(memcache, set);
PANDA_METHOD(memcache, get);
PANDA_METHOD(memcache, delete);
PANDA_METHOD(memcache, close);
PANDA_METHOD(memcache, addserver);

PANDA_FUNCTION(memcache_connect);
PANDA_FUNCTION(memcache_pconnect);
PANDA_FUNCTION(memcache_add_server);
PANDA_FUNCTION(memcache_set);
PANDA_FUNCTION(memcache_get);
PANDA_FUNCTION(memcache_delete);
PANDA_FUNCTION(memcache_close);
#endif
