#ifndef PHP_PANDA_MYSQLI_H
#define PHP_PANDA_MYSQLI_H
#define PANDA_EXPENDS_EXT_MYSQLI "mysqli"
#define PANDA_EXPENDS_EXT_MYSQLI_DEFAULT_PROT  3306

#define PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI "mysqli"
#define PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_STMT "mysqli_stmt"
#define PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_METHOD_MYSQLI "mysqli"
#define PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_METHOD_SELECT_DB "select_db"
#define PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_METHOD_QUERY "query"
#define PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_METHOD_PREPARE "prepare"
#define PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_METHOD_STMT_INIT "stmt_init"
#define PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_STMT_METHOD_EXECUTE "execute"
#define PANDA_EXPENDS_EXT_MYSQLI_CLS_MYSQLI_STMT_METHOD_PREPARE "prepare"

#define PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_CONNECT "mysqli_connect"
#define PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_SELECT_DB "mysqli_select_db"
#define PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_QUERY "mysqli_query"
#define PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_PREPARE "mysqli_prepare"
#define PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_STMT_INIT "mysqli_stmt_init"
#define PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_STMT_PREPARE "mysqli_stmt_prepare"
#define PANDA_EXPENDS_EXT_MYSQLI_FUNC_MYSQLI_STMT_EXECUTE "mysqli_stmt_execute"

PANDA_METHOD(mysqli, mysqli);
PANDA_METHOD(mysqli, select_db);
PANDA_METHOD(mysqli, query);
PANDA_METHOD(mysqli, prepare);
PANDA_METHOD(mysqli, stmt_init);
PANDA_METHOD(mysqli_stmt, execute);
PANDA_METHOD(mysqli_stmt, prepare);

PANDA_FUNCTION(mysqli_connect);
PANDA_FUNCTION(mysqli_select_db);
PANDA_FUNCTION(mysqli_query);
PANDA_FUNCTION(mysqli_prepare);
PANDA_FUNCTION(mysqli_stmt_init);
PANDA_FUNCTION(mysqli_stmt_execute);
#endif

