#ifndef PHP_PANDA_MYSQL_H
#define PHP_PANDA_MYSQL_H

#define PANDA_EXPENDS_EXT_MYSQL "mysql"

#define PANDA_EXPENDS_EXT_MYSQL_DEFAULT_HOST "127.0.0.1"
#define PANDA_EXPENDS_EXT_MYSQL_DEFAULT_PROT  3306
#define PANDA_EXPENDS_EXT_MYSQL_FUNC_MYSQL_CONNECT "mysql_connect"
#define PANDA_EXPENDS_EXT_MYSQL_FUNC_MYSQL_QUERY "mysql_query"
#define PANDA_EXPENDS_EXT_MYSQL_FUNC_MYSQL_SELECT_DB "mysql_select_db"


PANDA_FUNCTION(mysql_connect);
PANDA_FUNCTION(mysql_query);
PANDA_FUNCTION(mysql_select_db);
#endif
